name: Build and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-central-1
  SERVER_STACK_NAME: nat-test-resources
  CNAME: cellprobe.thingy.rocks

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Compile TypeScript
        run: npx tsc
      - name: Test
        run: npm test
      - name: Determine next release version
        id: next-version
        if: endsWith(github.ref, 'saga')
        continue-on-error: true
        run: node .github/workflows/get-next-version.js > .version
      - name: Fetch configuration
        run: node cli app-config > .env
      - name: Build
        run: |
          export $(cat .env | xargs)
          npm run build
          node scripts/renderIndex.js > public/index.html
          cp web/logo.svg public
      - name: Publish build to gh-pages
        if:
          contains(github.ref, 'saga') && steps.next-version.conclusion ==
          'success'
        run: |
          echo "machine github.com login authtoken password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          cd public
          echo ${CNAME} > CNAME
          git init
          git add ./*
          git commit -m "📦 publish `cat ../.version | tr -d '\n'`"
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git push -f origin HEAD:gh-pages
      - name: Semantic release
        continue-on-error: true
        run: npx semantic-release
